"""Build the theme Custom Liquid snippet that adds calls to action under articles.

One snippet, pasted into the theme editor (Blog posts -> Default blog post -> the
Custom Liquid section under "Blog post"), renders:
  * on "<breed>-first-year-costs" guides: a box linking to the cost calculator
    with that breed preselected;
  * on the breed guides that are in the quiz: "Is the <Breed> right for you?"
    linking to the breed quiz in breed-entry mode (?breed=<slug>).
Everything else renders nothing. No article content, title, meta or "last
updated" date changes, so it is safe to use while title tests are running.

The breed list comes from breed-quiz-data.json, so re-run this after adding
breeds and paste the new output over the old code.

Usage: py scripts/build_theme_cta_snippet.py
"""

import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_PATH = os.path.join(ROOT, "breed-quiz-data.json")
OUT_PATH = os.path.join(ROOT, "pages", "theme-custom-liquid-article-ctas.liquid")
SAFE_SLUG = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
UNSAFE_NAME = re.compile(r'[|,"\n\r{}%]')

BOX = ("background:#faf7f2;border:1px solid rgba(0,0,0,0.08);border-radius:16px;"
       "padding:20px 22px;margin:8px 0 32px;")
TITLE = "margin:0 0 6px;font-weight:700;font-size:17px;line-height:1.4;color:#1a1a1a;"
BODY = "margin:0 0 14px;font-size:15px;line-height:1.6;color:#5c6166;"
BUTTON = ("display:inline-block;background:#108474;color:#ffffff;font-weight:700;font-size:15px;"
          "padding:11px 20px;border-radius:10px;text-decoration:none;")

TEMPLATE = """{%- comment -%}
  Wooffy article calls to action. Generated by scripts/build_theme_cta_snippet.py from
  breed-quiz-data.json (__COUNT__ quiz breeds) - edit the script, not this output.
  Theme editor -> Blog posts -> Default blog post -> Custom Liquid section under "Blog post"
  (padding 0/0). Renders nothing on other articles.
{%- endcomment -%}
{%- if article -%}
  {%- assign wf_handle = article.handle | split: '/' | last -%}
  {%- if wf_handle contains '-first-year-costs' -%}
    {%- assign wf_breed = wf_handle | remove: '-first-year-costs' -%}
    <div class="page-width page-width--narrow">
      <div style="__BOX__">
        <p style="__TITLE__">Estimate your own first-year costs</p>
        <p style="__BODY__">Change where you live, breeder or rescue, insurance and grooming. The calculator adds up every line item for this breed.</p>
        <a href="/pages/dog-cost-calculator?breed={{ wf_breed | url_encode }}" style="__BUTTON__">Open the cost calculator</a>
      </div>
    </div>
  {%- else -%}
    {%- assign wf_pairs = "__PAIRS__" | split: ',' -%}
    {%- assign wf_name = '' -%}
    {%- for wf_pair in wf_pairs -%}
      {%- assign wf_kv = wf_pair | split: '|' -%}
      {%- if wf_kv[0] == wf_handle -%}{%- assign wf_name = wf_kv[1] -%}{%- break -%}{%- endif -%}
    {%- endfor -%}
    {%- if wf_name != '' -%}
      <div class="page-width page-width--narrow">
        <div style="__BOX__">
          <p style="__TITLE__">Is the {{ wf_name | escape }} right for you?</p>
          <p style="__BODY__">Answer 12 quick questions about your home, schedule and family. We&rsquo;ll show how well the {{ wf_name | escape }} fits your life, and which breeds fit even better.</p>
          <a href="/pages/dog-breed-quiz?breed={{ wf_handle | url_encode }}" style="__BUTTON__">Check your fit</a>
        </div>
      </div>
    {%- endif -%}
  {%- endif -%}
{%- endif -%}
"""


def main() -> None:
    breeds = json.load(open(DATA_PATH, encoding="utf-8"))["breeds"]
    pairs = []
    for b in breeds:
        slug, name = b["s"], b["n"]
        if not SAFE_SLUG.match(slug) or UNSAFE_NAME.search(name):
            raise SystemExit(f"unsafe slug/name for the Liquid list: {slug!r} / {name!r}")
        pairs.append(f"{slug}|{name}")
    out = (TEMPLATE.replace("__PAIRS__", ",".join(pairs)).replace("__COUNT__", str(len(pairs)))
           .replace("__BOX__", BOX).replace("__TITLE__", TITLE).replace("__BODY__", BODY)
           .replace("__BUTTON__", BUTTON))
    with open(OUT_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write(out)
    print(f"wrote {OUT_PATH} ({len(pairs)} breeds, {len(out.encode('utf-8')):,} bytes)")


if __name__ == "__main__":
    main()
